// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69U9sbFSNFgSR15e_g2309NOXL7wbh68',
    authDomain: 'ddirectaui.firebaseapp.com',
    projectId: 'ddirectaui',
    storageBucket: 'ddirectaui.appspot.com',
    messagingSenderId: '208058583398',
    appId: '1:208058583398:web:e300cb6186f1f11063e0a7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69U9sbFSNFgSR15e_g2309NOXL7wbh68',
    appId: '1:208058583398:android:e300cb6186f1f11063e0a7',
    messagingSenderId: '208058583398',
    projectId: 'ddirectaui',
    storageBucket: 'ddirectaui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4SSXFDQ6gSOsgn-VekX832TbUQUEQHg',
    appId: '1:208058583398:ios:c6b3b4990bd6ef7463e0a7',
    messagingSenderId: '208058583398',
    projectId: 'ddirectaui',
    storageBucket: 'ddirectaui.appspot.com',
    iosBundleId: 'com.example.prueba',
  );
}
